version: 2.1
orbs:
  android: circleci/android@2.1.2
  ruby: circleci/ruby@2.0.0
references:
  release_key: &release_key
    run:
      name: Create keystore
      command: |
        echo $RELEASE_KEY | base64 -d > ~/release.jks
        echo $GOOGLE_TOKEN | base64 -d > ~/project/google_token.json
  fastlane_deploy: &fastlane_deploy
    run:
        name: Fastlane
        command: |
          bundle exec fastlane deploy jks_path:/home/circleci/release.jks gradle_path:$GRADLE_PATH store_password:$RELEASE_STORE_PASS key_alias:$RELEASE_ALIAS key_password:$RELEASE_KEY_PASS
jobs:
  release-build:

    executor:
      name: android/android-machine
      resource-class: large
      tag: 2022.09.1

    steps:
      - checkout
      - *release_key
      - ruby/install-deps
      - *fastlane_deploy
workflows:
  build:
    jobs:
      - release-build:
          filters:
            branches:
              only:
                - main