# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Deploy a new version to the App Distribution"
  lane :deploy do |options|

  release_notes = " "

    gradle(
      task: "bundle",
      build_type: "Release",
      properties: {
        "android.injected.signing.store.file" => options[:jks_path],
        "android.injected.signing.store.password" => options[:store_password],
        "android.injected.signing.key.alias" => options[:key_alias],
        "android.injected.signing.key.password" => options[:key_password],
      }
    )

    upload_to_play_store(track: 'production')     

  end

end
